AWSTemplateFormatVersion: '2010-09-09'
Description: 'S3 Bucket Policy for CloudFront CMCD stack'

Parameters:
  MainStackName:
    Type: String
    Description: Name of the main CloudFront CMCD stack
    Default: cmcd-kinesis-stack

Resources:
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: 
        Fn::ImportValue: !Sub '${MainStackName}-S3BucketName'
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: s3:GetObject
            Resource: !Sub 
              - '${BucketArn}/*'
              - BucketArn: 
                  Fn::Sub:
                    - 'arn:aws:s3:::${BucketName}'
                    - BucketName:
                        Fn::ImportValue: !Sub '${MainStackName}-S3BucketName'
            Condition:
              StringEquals:
                'AWS:SourceArn': !Sub 
                  - 'arn:aws:cloudfront::${AWS::AccountId}:distribution/${DistributionId}'
                  - DistributionId:
                      Fn::ImportValue: !Sub '${MainStackName}-CloudFrontDistributionId'